CREATE TABLE IF NOT EXISTS practicas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    cod_univ VARCHAR(20),
    raz_soc VARCHAR(150),
    facultad VARCHAR(100),
    prim_ape VARCHAR(50),
    seg_ape VARCHAR(50),
    nombre VARCHAR(100),
    sexo CHAR(1),
    tipo_doc VARCHAR(10),
    nro_doc VARCHAR(20),
    fecha_matri DATE,
    fecha_egreso DATE,
    ciclo_egreso VARCHAR(10),
    reg_oficio VARCHAR(50),
    codigo_practica VARCHAR(50),
    empresa VARCHAR(150),
    area VARCHAR(100),
    cargo VARCHAR(100),
    abre_gyt VARCHAR(10),
    carrera VARCHAR(100),
    grado VARCHAR(100),
    programa VARCHAR(100),
    creditos INT,
    mod_obt VARCHAR(50),
    mod_est VARCHAR(50),
    fecha_inicio DATE,
    resolucion VARCHAR(50),
    fecha_resol DATE,
    dipl_fec_org DATE,
    nro_diploma VARCHAR(50),
    reg_libro INT,
    reg_folio INT,
    reg_registro VARCHAR(50),
    cargo_1 VARCHAR(50), autoridad_1 VARCHAR(100),
    cargo_2 VARCHAR(50), autoridad_2 VARCHAR(100),
    cargo_3 VARCHAR(50), autoridad_3 VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO practicas (
    cod_univ, raz_soc, facultad, prim_ape, seg_ape, nombre, sexo, tipo_doc, nro_doc, 
    fecha_matri, fecha_egreso, ciclo_egreso, reg_oficio, codigo_practica, empresa, 
    area, cargo, abre_gyt, carrera, grado, programa, creditos, mod_obt, mod_est, 
    fecha_inicio, resolucion, fecha_resol, dipl_fec_org, nro_diploma, reg_libro, 
    reg_folio, reg_registro, cargo_1, autoridad_1, cargo_2, autoridad_2, cargo_3, autoridad_3
) VALUES (
    '043', 'UNIVERSIDAD PRIVADA DE TACNA', 'INGENIERIA', 'LIZARRAGA', 'POMAREDA', 
    'SERGIO PEDRO', 'M', '1', '71194900', '2020-03-02', '2025-07-04', 'X', 
    '001-2026-UPT-REDO-SG', '2020066921', 'MUNICIPALIDAD PROVINCIAL DE TACNA', 
    'Area de Informatica', 'Desarrollador', 'B', 'INGENIERIA DE SISTEMAS', 
    'BACHILLER EN INGENIERIA DE SISTEMAS', 'CICLO REGULAR', 225, 'CURSO "TRABAJO DE INVESTIGACION" X CICLO', 
    'P', '2025-12-02', '2760-2025-UPT-R', '2025-12-02', '2025-12-04', 'UPT15191', 
    15, 63, '17612-25', 'RECTOR', 'CALIZAYA CALIZAYA HUGO CIRILO', 'SECRETARIA GENERAL', 
    'IBARRA MONTECINOS MARIELLA', 'DECANO', 'ZEGARRA ALVARADO NORIBAL'
);      